# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-29 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_cit', models.CharField(max_length=100)),
                ('country_dest', models.CharField(max_length=100)),
                ('visa_needed', models.BooleanField(default=True)),
            ],
        ),
    ]
