# Generated by Django 3.2.20 on 2023-09-01 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='country_cit',
            new_name='destination',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='country_dest',
            new_name='home_country',
        ),
    ]
