# Generated by Django 3.2.20 on 2023-09-01 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visas', '0002_auto_20230901_1018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='home_country',
            new_name='citizen_country',
        ),
    ]
