# Generated by Django 3.2.20 on 2023-09-01 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visas', '0003_rename_home_country_entry_citizen_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='visa_needed',
        ),
        migrations.AddField(
            model_name='entry',
            name='visa_type',
            field=models.CharField(choices=[('VF', 'Visa Free'), ('VOA', 'Visa on Arrival (including eTA)'), ('VR', 'Visa Required'), ('CB', 'Covid Ban'), ('NA', 'No Admission'), ('??', 'Unknown')], default='??', max_length=3),
        ),
    ]
